Code refactoring
jugendhacker/plugin.audio.mstream pull request #2
Opened 2018-10-13 18:46 UTC by illright

This PR improves code readability and maintainability by refactoring the addon functionality into a class.
Also it adds some advanced command-line args parsing for easier usage.

Fixes #1

2018-10-13 19:08 UTC, jugendhacker requested changes
Please solve this problems, but I'm also not sure if you're familar with the programming of kodi plugins becuase this doesn't work at the moment! Please test it before you submit a pull request!

2018-10-13 19:08 UTC, jugendhacker commented on addon.py
> +import urllib.parse
You need that urlparse because urllib.parse doesn't exist on a kodi, did you tested this?

2018-10-13 19:08 UTC, jugendhacker commented on addon.py
> +    args = parser.parse_args()
The whole args thing doesn't work, I think because Kodi is calling the plugins in a diffrent way...

2018-10-13 19:19 UTC, illright commented
I'm not familiar with writing Kodi plugins, just Python programming in general. Neither do I have a Kodi to test this..

The args thing can be fixed up to be called like the previous code.

About `urlparse`, which Python version is running on Kodi? Why is there no `urllib.parse`?

2018-10-13 19:24 UTC, jugendhacker commented
You could easily setup a kodi for testing...

> The args thing can be fixed up to be called like the previous code.

Please change this so that this will work again

> About urlparse, which Python version is running on Kodi? Why is there no urllib.parse?

Not sure but I think their own Kind of python2

2018-10-14 16:11 UTC, jugendhacker commented on addon.py
> +    args = parser.parse_args()
Still fails with
```
18:09:53.207 T:6296   ERROR: usage: [-h] base_url addon_handle {files,play} path
18:09:53.207 T:6296   ERROR: : error: argument addon_handle: invalid int value: ''
```
Please set you up a Kodi for testing, I can't do every testing for you, that's not the way how PRs work

2018-10-14 16:13 UTC, jugendhacker commented
Doesn't work, please look at the comment, I provided a log

2018-10-14 16:16 UTC, jugendhacker commented
Why you closed this PR?

2018-10-14 16:16 UTC, jugendhacker commented
Your refactoring is good but we need to resolve the calling part...

2018-10-14 16:17 UTC, illright commented
I do not own a Kodi so I simply can't test it. So we will have to compromise here.

2018-10-14 16:18 UTC, jugendhacker commented
Kodi is a piece of software so you could install it on every pc...

2018-10-14 16:21 UTC, jugendhacker commented
I really want to merge these changes but we need to rework the starup part before, you also don't need a kodi you could also read about how to do it [in the kodi wiki](https://kodi.wiki/view/Add-on_development)

2018-10-15 10:58 UTC, jugendhacker commented
Please give me a answer....

2018-10-15 11:01 UTC, illright commented
I'll get the argument parsing there way it was before, but I don't know
when I'll get around to that. Sorry for the delay

пн, 15 окт. 2018 г., 13:58 jugendhacker <notifications@github.com>:

> Please give me a answer....
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/jugendhacker/plugin.audio.mstream/pull/2#issuecomment-429804757>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AOVrlrQ6tes0U6Iw6YLIjvxK4dp-Oay4ks5ulGpGgaJpZM4XaxLJ>
> .
>

2018-10-15 11:05 UTC, jugendhacker commented
Ok no problem, I just thought you don't want to do this anymore...

2018-10-16 10:06 UTC, illright commented
@jugendhacker should [this line](https://github.com/jugendhacker/plugin.audio.mstream/blob/master/addon.py#L78) contain `[0]`?

2018-10-16 10:22 UTC, jugendhacker commented
> should this line contain [0]?

Yes because the path arg is an array with one entry... don't ask me why, I don't know it!

2018-10-16 10:36 UTC, jugendhacker requested changes
Please get a better way for doing this... e.g giving the operator the whole args object...

2018-10-16 10:36 UTC, jugendhacker commented on addon.py
> +    operator.act(args.get('mode'), args.get('path'))
There is a problem here when I call it the first time with mode=files because there is not path=...

2018-10-16 11:47 UTC, jugendhacker commented
That seems good, but I have no time for testing now, will do it after 4pm UTC

2018-10-17 11:31 UTC, jugendhacker commented
Still getting
```
Error Type: <type 'exceptions.TypeError'>
Error Contents: 'NoneType' object has no attribute '__getitem__'
 Traceback (most recent call last):
  File "C:\Users\Julian\AppData\Roaming\Kodi\addons\plugin.audio.mstream\addon.py", line 130, in <module>
   operator.act(args.get('mode', None), args.get('path', None))
  File "C:\Users\Julian\AppData\Roaming\Kodi\addons\plugin.audio.mstream\addon.py", line 119, in act
   self.play_song(path[0])
 TypeError: 'NoneType' object has no attribute '__getitem__'
```

2018-10-17 12:15 UTC, jugendhacker commented
Next error incomming
```
Error Type: <type 'exceptions.KeyError'>                                                                            
Error Contents: ('path',)                                                                                           
Traceback (most recent call last):                                                                                  
  File "C:\Users\Julian\AppData\Roaming\Kodi\addons\plugin.audio.mstream\addon.py", line 130, in <module>           
    operator.act(args.get('mode', None), args.get('path', None))                                                    
  File "C:\Users\Julian\AppData\Roaming\Kodi\addons\plugin.audio.mstream\addon.py", line 113, in act                
    self.list_folder_contents(self.folders[0])                                                                      
  File "C:\Users\Julian\AppData\Roaming\Kodi\addons\plugin.audio.mstream\addon.py", line 66, in list_folder_contents
    path=os.path.join(file['path'], file['name'])                                                                   
KeyError: ('path',)                                                                                                 
```

2018-10-18 16:04 UTC, jugendhacker commented
```
Error Type: <type 'exceptions.TypeError'>                                                                           
Error Contents: list indices must be integers, not str                                                              
Traceback (most recent call last):                                                                                  
  File "C:\Users\Julian\AppData\Roaming\Kodi\addons\plugin.audio.mstream\addon.py", line 132, in <module>           
    operator.act(args.get('mode', None), args.get('path', None))                                                    
  File "C:\Users\Julian\AppData\Roaming\Kodi\addons\plugin.audio.mstream\addon.py", line 115, in act                
    self.list_folder_contents(self.folders[0])                                                                      
  File "C:\Users\Julian\AppData\Roaming\Kodi\addons\plugin.audio.mstream\addon.py", line 66, in list_folder_contents
    path=os.path.join(response['contents']['path'],                                                                 
TypeError: list indices must be integers, not str                                                                   
```
New Error xD

2018-10-27 21:06 UTC, jugendhacker commented
Sorry was offline by a technical issue with my Laptop, will test your latest commit tomorrow!

2018-10-28 11:09 UTC, jugendhacker commented
Now getting
```
Error Type: <type 'exceptions.UnicodeEncodeError'>                                                                  
Error Contents: 'ascii' codec can't encode character u'\u2019' in position 12: ordinal not in range(128)            
Traceback (most recent call last):                                                                                  
  File "C:\Users\Julian\AppData\Roaming\Kodi\addons\plugin.audio.mstream\addon.py", line 127, in <module>           
    operator.act(args.get('mode', None), args.get('path', None))                                                    
  File "C:\Users\Julian\AppData\Roaming\Kodi\addons\plugin.audio.mstream\addon.py", line 110, in act                
    self.list_folder_contents(self.folders[0])                                                                      
  File "C:\Users\Julian\AppData\Roaming\Kodi\addons\plugin.audio.mstream\addon.py", line 65, in list_folder_contents
    path=response['path'] + file['name']                                                                            
  File "C:\Users\Julian\AppData\Roaming\Kodi\addons\plugin.audio.mstream\addon.py", line 19, in build_url           
    return self.base_url + '?' + urllib.urlencode(query)                                                            
  File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib.py", line 1343, in urlencode                           
    v = quote_plus(str(v))                                                                                          
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 12: ordinal not in range(128)        
```

2018-11-08 18:57 UTC, jugendhacker commented
Now it does something wrong with the url Encoding...
It requests `http://server:3000/media/music%2FAdele%2FSkyfall.mp3?token=...` instead of `http://server:3000/media/music/Adele/Skyfall.mp3?token=...`

2018-11-09 15:04 UTC, illright commented
The good intentions are at fault :p shouldn't have changed any functions

2018-11-13 16:23 UTC, jugendhacker commented
The Problem is this strange kodi python engine xD

2018-11-13 16:27 UTC, jugendhacker commented
But thank you, now everything works!

2018-11-13 16:27 UTC, jugendhacker approved these changes

2018-11-13 16:29 UTC, merged